---
version: '3'

vars:
  IMAGE: nicholaswilde/mkdocs-material
  PORT: 8000

tasks:
  build:
    desc: Build documentation using Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -v ${PWD}:/docs --platform linux/amd64
        {{ .IMAGE }} build -f ./mkdocs.yml
  clean:
    desc: Remove the previous checksum file
    cmds:
      - rm /tmp/checksum
      - rm -r ./vaultwarden-*
    ignore_error: true
  purge:
    desc: Purge old files
    cmds:
      - find "./archives" -name 'vaultwarden-*.tar.*' -mtime +14 -delete
  logs:
    desc: Show logs
    cmds:
      - journalctl -t rclone --no-pager
      - journalctl -t vaultwarden-backup --no-pager
  backup:
    desc: Run backup.sh
    cmds:
      - ./backup.sh
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt update
      - sudo apt install rclone
      - pipx install apprise
  init:
    desc: Init
    cmds:
      - cp backup.conf.tmpl backup.conf
  serve:
    desc: >-
      Start development server on http://0.0.0.0:{{ .PORT }} using
      Docker and mkdocs-material
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT}} -v ${PWD}:/docs
        --platform linux/amd64 {{ .IMAGE }} serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
    deps:
      - build
  default:
    cmds:
      - task -l
    silent: true
