---
version: '3'

tasks:
  clean:
    desc: Remove the previous checksum file
    cmds:
      - rm /tmp/checksum
      - rm -r ./vaultwarden-*
    ignore_error: true
  purge:
    desc: Purge old files
    cmds:
      - find "./archives" -name 'vaultwarden-*.tar.*' -mtime +14 -delete
  logs:
    desc: Show logs
    cmds:
      - journalctl -t rclone --no-pager
      - journalctl -t vaultwarden-backup --no-pager
  backup:
    desc: Run backup.sh
    cmds:
      - ./backup.sh
  deps:
    desc: Install dependencies
    cmds:
      - sudo apt update
      - sudo apt install rclone
      - pipx install apprise
  init:
    desc: Init
    cmds:
      - cp backup.conf.tmpl backup.conf
  default:
    cmds:
      - task -l
    silent: true
